### ISSUE TITLE
CMake uses wrong PythonLibs

### ISSUE THREAD

**Issue by pgdurand** [GATB/pyGATB#1]
On OSX, I did:
```bash
cd <some_fresh_dir>
git clone https://github.com/GATB/pyGATB.git
mkdir build ; cd build;
cmake -DCMAKE_BUILD_TYPE=Release ..
```
While checking at the CMale working trace, I saw this:

```
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 (found version "3.4.4") 
-- Found Cython: /Library/Frameworks/Python.framework/Versions/3.4/bin/cython  
-- Found PythonLibs: /usr/lib/libpython2.7.dylib (found version "2.7.10") 
```
Where there is the problem: PythonInterp **3.4.4** vs. PythonLibs **2.7.10**.

How can we fix that?

**Comment by pgdurand** [comment]
Depending on the way Python3 was installed on OSX, such a problem is known to occur.

There is a simple way to solve that (as stated in the pyGATB wiki, [here](https://github.com/GATB/pyGATB/wiki/Use-pyGATB-from-its-source-code#if-you-have-installed-python3-using-an-installer)). On the command-line, start CMake as follows:

```bash
cmake -DCMAKE_BUILD_TYPE=Release .. \
-DPYTHON_LIBRARY="/Library/Frameworks/Python.framework/Versions/3.4/lib/libpython3.4.dylib"\
 -DPYTHON_INCLUDE_DIR="/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m"
```
Of course, adapt full paths to Python 3 library and Python 3 include file to the ones of your system.

As a results of the above command, I got this (CMake working trace):

```
-- Found PythonInterp: /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4 (found version "3.4.4") 
-- Found PythonLibs: /Library/Frameworks/Python.framework/Versions/3.4/lib/libpython3.4.dylib (found version "3.4.4") 
```
All fine: Python 3.4.4 is used!

**Comment by Piezoid** [comment]
The pyGATB doesn't link against the libpython (it's not recommended)
